version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup-node"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup-eas"
    schedule:
      interval: "weekly"
