packages:
  - apps/*

catalog:
  prettier: 3.8.1

nodeLinker: hoisted

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  ajv@<8.18.0: '>=8.18.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  minimatch@<10.2.1: '>=10.2.1'
  on-headers@<1.1.0: '>=1.1.0'
  tar@<7.5.8: '>=7.5.8'
  undici@<6.23.0: '>=6.23.0'
