name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node

      - name: Generate Expo types
        run: pnpm --dir apps/sandbox run generate-types

      - name: Run Oxlint
        run: |
          pnpm exec oxlint --type-aware --type-check --format=github apps/sandbox
          pnpm exec oxlint --type-aware --type-check --format=github packages/tooling

      - name: Run expo lint
        run: pnpm --dir apps/sandbox run lint:expo

      - name: Check formatting
        run: pnpm -r run lint:oxfmt

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node

      - name: Run tests
        run: pnpm -r run test
