name: eas-update

on:
  push:
    branches:
      - main

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node

      - name: Setup EAS
        uses: ./.github/actions/setup-eas
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Run EAS Update
        run: eas update --auto --branch development
        working-directory: apps/sandbox
