name: eas-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "EXPO_TOKEN is not set. Skipping EAS Build."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: pnpm

      - name: Run EAS Build
        run: eas build --profile development --platform all --non-interactive
        working-directory: apps/sandbox
