name: eas-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node

      - name: Setup EAS
        uses: ./.github/actions/setup-eas
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Run EAS Build
        run: eas build --profile development --platform android --non-interactive
        working-directory: apps/sandbox
