name: preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'apps/sandbox/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
      - '.github/workflows/preview.yml'
      - '.github/actions/**'

jobs:
  update:
    name: EAS Update
    if: github.event.action != 'closed' && github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node

      - name: Setup EAS
        uses: ./.github/actions/setup-eas
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --branch ${{ github.event.pull_request.head.ref }} --message "${{ github.event.pull_request.title }}"
          working-directory: apps/sandbox

  delete-branch:
    name: Delete EAS Update Branch
    if: github.event.action == 'closed' && github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node

      - name: Setup EAS
        uses: ./.github/actions/setup-eas
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Delete EAS Update branch
        run: eas branch:delete ${{ github.event.pull_request.head.ref }} --non-interactive
        working-directory: apps/sandbox
